---
- hosts: webservers
  remote_user: ansible
  become: yes
  tasks:
    - name: create a folder example
      file: 
         path: /tomcatfiles
         state: directory
         mode: '0777'


    - name: download warfile
      ansible.builtin.git: 
         repo: 'https://github.com/dheerajkolla/addressbook.war.git'
         dest: /tomcatfiles