---
- hosts: webservers
  remote_user: ansible
  become: yes
  tasks:
    - name: Install JAVA related Ubuntu packages
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - openjdk-8-jdk
          - tomcat9
          - tomcat9-examples
          - tomcat9-docs

    - name: copy war
      shell:
        cmd: cp /home/ansible/example/addressbook.war /var/lib/tomcat9/webapps/addressbook.war
     
    - name: Make sure a service is running
      ansible.builtin.systemd:
        state: started
        enabled: true
        name: tomcat9
    
    - name: Open Tomcat port
      ufw:
        state: enabled
        rule: allow
        port: "8080"
